1

diff --git a/web_server/0-transfer_file b/web_server/0-transfer_file
--- a/web_server/0-transfer_file
+++ b/web_server/0-transfer_file
@@ -1,17 +1,25 @@
-#!/usr/bin/env bash
-# Transfers a file from client to server using scp
+#!/usr/bin/env bash 
+#Write a Bash script that transfers a file from our client to a server:
 
-# Check if exactly 4 parameters are provided
-if [ "$#" -ne 4 ]; then
-    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-    exit 1
+# check if there are enough parameters
+if [ $# -lt 4 ]; then
+  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+  exit 1
 fi
 
-# Assign arguments to variables
-FILE_PATH=$1
-SERVER_IP=$2
-SERVER_USER=$3
-SSH_KEY=$4
+# set variables for the parameters
+file_path="$1"
+server_ip="$2"
+username="$3"
+ssh_key="$4"
 
-# Transfer file to the user's home directory on the server
-scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE_PATH" "$SERVER_USER@$SERVER_IP:~/"
+# transfer the file using scp
+scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username"@"$server_ip":~/
+
+# check the exit code of scp
+if [ $? -eq 0 ]; then
+  echo "File transfer successful"
+else
+  echo "File transfer failed"
+fi
+
